#!/bin/bash
echo "Make sure git and curl are installed to get this setup working!"
echo "Installing oh-my-zsh shell."
curl -L http://install.ohmyz.sh | sh

if [ ! -d ~/.dotfiles_backup ]; then
  echo "Creating backup directory."
  mkdir ~/.dotfiles_backup
fi

if [ -e ~/.zshrc ]; then
    mv ~/.zshrc ~/.dotfiles_backup
    echo ".zshrc Backed up"
fi

if [ -e ~/.tmux.conf ]; then
    mv ~/.tmux.conf ~/.dotfiles_backup
    echo ".tmux.conf Backed up"
fi

echo "Creating dotfiles symlinks"
ln -nsf "$PWD"/zshrc ~/.zshrc
ln -nsf "$PWD"/tmux.conf ~/.tmux.conf

echo "I'll clone dotvim now:"
git clone https://github.com/gabrielalmeida/dotvim ~/dotvim
echo "Starting dotvim setup automatically!"
~/dotvim/setup

echo "Dotfiles setup is complete"
echo "If you are not on zsh shell yet, do: \$zsh"
